### ISSUE TITLE
Wrong artifactId in state artifact deployment

### ISSUE THREAD

**Issue by goeblj** [SAP/cloud-s4-sdk-pipeline-lib#10]
The script stageArtifactDeployment.groovy reads on line 16 the pom.xml from the main project. The jar files are coming from application/target/*.jar (line 21). The result is that in nexus is an artefact with artefactId with out -application. In a test project i did an dependency to this  project (artefactId with -application) and it's works local. If the project runs through the jenkins pipeline it doesn't work because the dependency is not found. If i change to the nexus dependency without -application local testing is not possible with opened referenced project.

Regards Jürgen

**Comment by rkamath3** [comment]
Hello @goeblj 

Thanks for bringing this bug to our notice. We are working on the fix. We will notify you once the fix is publicly available.

Regards 
Ram

**Comment by kurzy** [comment]
Fixed by https://github.com/SAP/cloud-s4-sdk-pipeline-lib/commit/1ab772bf18006fe306e37b8a123f369a0d154374

We changed the behavior. No we are deploying both the pom file in the root and the artifact, e.g. jar file, in the application folder as xyz-application.jar
Hope that works for you.
